/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { APIRequest, TransportConnectionParams } from '@pipecat-ai/client-js';

export type TransportType = 'daily' | 'smallwebrtc' | 'websocket';

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  'smallwebrtc',
];

export const DEFAULT_TRANSPORT: TransportType = 'smallwebrtc';

export const TRANSPORT_LABELS: Record<TransportType, string> = {
  daily: 'Daily',
  smallwebrtc: 'SmallWebRTC',
  websocket: 'WebSocket',
};

const dailyConfig: APIRequest = {
  endpoint: '/api/start',
  requestData: {
    createDailyRoom: true,
    dailyRoomProperties: { start_video_off: true },
    transport: 'daily',
  },
};

const smallWebRTCConfig: APIRequest = {
  endpoint: '/api/start',
  requestData: {
    createDailyRoom: false,
    enableDefaultIceServers: true,
    transport: 'webrtc',
  },
};

const websocketConfig: APIRequest = {
  endpoint: '/api/start',
  requestData: {
    transport: 'websocket',
  },
};

/**
 * Append the connection token (if any) to the WebSocket URL returned by the
 * server before the transport connects.
 */
const websocketResponseTransformer = (
  response: TransportConnectionParams
): TransportConnectionParams => {
  const { wsUrl, token } = response as { wsUrl: string; token?: string };
  return {
    wsUrl: token ? `${wsUrl}?token=${encodeURIComponent(token)}` : wsUrl,
  };
};

/**
 * Props passed to `PipecatAppBase` for each transport. WebRTC transports
 * connect in one step via `connectParams`; WebSocket starts the bot first and
 * transforms the response into the WebSocket connection params.
 */
export interface TransportProps {
  connectParams?: APIRequest | TransportConnectionParams;
  startBotParams?: APIRequest;
  startBotResponseTransformer?: (
    response: TransportConnectionParams
  ) => TransportConnectionParams | Promise<TransportConnectionParams>;
}

export const TRANSPORT_PROPS: Record<TransportType, TransportProps> = {
  daily: { connectParams: dailyConfig },
  smallwebrtc: { connectParams: smallWebRTCConfig },
  websocket: {
    startBotParams: websocketConfig,
    startBotResponseTransformer: websocketResponseTransformer,
  },
};

/** The three switchable pipeline layers, in pipeline order. */
export const MODEL_LAYERS = ['stt', 'llm', 'tts'] as const;
export type ModelLayer = (typeof MODEL_LAYERS)[number];

export const LAYER_LABELS: Record<ModelLayer, string> = {
  stt: 'Speech-to-Text',
  llm: 'Language Model',
  tts: 'Text-to-Speech',
};

/** One selectable model, as returned by the bot's `/models` endpoint. */
export interface ModelOption {
  id: string;
  label: string;
}

export type ModelSelection = Record<ModelLayer, string>;

/** Shape of `/api/models` (proxied from the bot's `/models`). */
export interface ModelsResponse {
  stt: ModelOption[];
  llm: ModelOption[];
  tts: ModelOption[];
  defaults: ModelSelection;
}

/**
 * Build the SmallWebRTC connect params for a given model selection. The
 * selection rides along in `requestData.body`, which the Pipecat runner hands
 * to the bot as `runner_args.body` (see server/bot.py `run_bot`).
 */
export const buildConnectParams = (
  selection: ModelSelection
): APIRequest => ({
  endpoint: '/api/start',
  requestData: {
    createDailyRoom: false,
    enableDefaultIceServers: true,
    transport: 'webrtc',
    body: selection,
  },
});